### PR TITLE
Added fizzbuzz program with php

### PR DESCRIPTION
**Pull request by rinaldipratama**
I just added a simple PHP program to solving fizzbuzz problem.

### CODE REVIEW

**Review by Faiznurullah — CHANGES_REQUESTED** [review]
Lupa tutup tag PHP ?>  betulkan terlebih dahulu

**Comment by rinaldipratama** [comment]
Done

**Comment by rinaldipratama** [comment]
atau harus pull request lagi?

**Comment by Faiznurullah** [comment]
Dah sob

**Comment by rinaldipratama** [comment]
makasih bro

**Pull request merged**
