### PR TITLE
adding my program

### PR DESCRIPTION
**Pull request by rajanyadav857**

### CODE REVIEW

**Review by Faiznurullah — CHANGES_REQUESTED** [review]
When run error, please check your code

**Comment by rajanyadav857** [comment]
program is correct but there may be issue with online compiler. Some online compilers has fixed the class name so we can't give our own class name. For some compilers class should be public than only it will work.

you can run program on below compiler
https://www.w3schools.com/java/tryjava.asp?filename=demo_compiler

**Comment by Faiznurullah** [comment]
Pull request again

**Comment by rajanyadav857** [comment]
reopened the pull request

**Pull request merged**
